// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfwZlE3xjm8HebVRgmfTa2wGDMsArdAQ',
    appId: '1:140623359734:web:7dcfbbfe6b416fd2ecc6d7',
    messagingSenderId: '140623359734',
    projectId: 'todo-ef04c',
    authDomain: 'todo-ef04c.firebaseapp.com',
    storageBucket: 'todo-ef04c.firebasestorage.app',
    measurementId: 'G-Z343LXV3MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCes3692ahA9UM7vLzQbjrYD7ARrK9bX0Y',
    appId: '1:140623359734:android:f243042cc02a020decc6d7',
    messagingSenderId: '140623359734',
    projectId: 'todo-ef04c',
    storageBucket: 'todo-ef04c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQH2-vsoUL_BN2-d5k2ZJSjZ1Ft8cAhiw',
    appId: '1:140623359734:ios:98751da05f41296aecc6d7',
    messagingSenderId: '140623359734',
    projectId: 'todo-ef04c',
    storageBucket: 'todo-ef04c.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQH2-vsoUL_BN2-d5k2ZJSjZ1Ft8cAhiw',
    appId: '1:140623359734:ios:98751da05f41296aecc6d7',
    messagingSenderId: '140623359734',
    projectId: 'todo-ef04c',
    storageBucket: 'todo-ef04c.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADfwZlE3xjm8HebVRgmfTa2wGDMsArdAQ',
    appId: '1:140623359734:web:1721b00d8531547decc6d7',
    messagingSenderId: '140623359734',
    projectId: 'todo-ef04c',
    authDomain: 'todo-ef04c.firebaseapp.com',
    storageBucket: 'todo-ef04c.firebasestorage.app',
    measurementId: 'G-XTGR8Y55WB',
  );

}